### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by Senal27** [greghub/vue-funnel-graph-js#11]
**vue-funnel-graph-js** Version : ^0.1.6
**Vue** Version : 2.6.10
**Nuxt** Version: ^2.0.0

I try to use this component with my nuxt project but project end up with the above error msg

**Comment by Paalt** [comment]
I do too in my nuxt project. I only get it when refreshing the browser. The first load works fine. Commenting out the import fixes the error, commenting out the component only does not. 

`SyntaxError
Unexpected token {
vm.js
Missing stack frames 
Js
new Script@85:7
vm.js:85:7
new Script
vm.js:266:10
createScript
vm.js:314:10
Object.runInThisContext
internal/modules/cjs/loader.js:698:28
Module._compile
internal/modules/cjs/loader.js:749:10
Module._extensions..js
internal/modules/cjs/loader.js:630:32
Module.load
internal/modules/cjs/loader.js:570:12
tryModuleLoad
internal/modules/cjs/loader.js:562:3
Module._load
internal/modules/cjs/loader.js:667:17
Module.require
internal/modules/cjs/helpers.js:20:18
`

**Comment by Paalt** [comment]
/node_modules/funnel-graph-js/src/js/main.js:2
import { roundPoint, formatNumber } from './number';
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:85:7)
    at createScript (vm.js:266:10)
    at Object.runInThisContext (vm.js:314:10)
    at Module._compile (internal/modules/cjs/loader.js:698:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/paltaulebrentebraten/Documents/Apps/solidsquare.no/posten/PostenSignage/node_modules/funnel-graph-js/index.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)

I get this error when trying to run 'npm run generate'. Running 'npm run build', works though
